init:
  home: "$HOME/.squadapp"
accounts:
  - name: alice # cosmos1zaavvzxez0elundtn32qnk9lkm8kmcszzsv80v
    mnemonic: "guard cream sadness conduct invite crumble clock pudding hole grit liar hotel maid produce squeeze return argue turtle know drive eight casino maze host"
    coins: ["1500000000000stake", "1000000000000000uatom", "1000000000000000uusd"]
  - name: bob # cosmos1mzgucqnfr2l8cj5apvdpllhzt4zeuh2cshz5xu
    mnemonic: "friend excite rough reopen cover wheel spoon convince island path clean monkey play snow number walnut pull lock shoot hurry dream divide concert discover"
    coins: ["1000000000000stake", "1000000000000000uatom", "1000000000000000uusd"]
  - name: steve # cosmos185fflsvwrz0cx46w6qada7mdy92m6kx4gqx0ny
    mnemonic: "fuel obscure melt april direct second usual hair leave hobby beef bacon solid drum used law mercy worry fat super must ritual bring faculty"
    coins: ["1000000000000stake", "1000000000000000uatom", "1000000000000000uusd"]
  - name: source # cosmos15rz2rwnlgr7nf6eauz52usezffwrxc0mz4pywr
    mnemonic: "diary behind allow lawn loop assault armor survey media toe rural mass skull way crater tobacco pair glare window soon lift pistol fitness annual"
    coins: ["15000000000000airdrop"]
validator:
  name: alice
  staked: "500000000000stake"
genesis:
  chain_id: "localnet"
  app_state:
    crisis:
      constant_fee:
        denom: "stake"
    mint:
      params:
        mint_denom: "stake"
    staking:
      params:
        bond_denom: "stake"
    gov:
      deposit_params:
        min_deposit:
          - amount: "1"
            denom: "stake"
    farming:
      params:
        private_plan_creation_fee:
          - amount: "1"
            denom: "stake"
    liquidity:
      params:
        pair_creation_fee:
          - amount: "1"
            denom: "stake"
        pool_creation_fee:
          - amount: "1"
            denom: "stake"
    liquidstaking:
      params:
        liquid_bond_denom: "bstake"
        whitelisted_validators:
          - validator_address: "cosmosvaloper1zaavvzxez0elundtn32qnk9lkm8kmcsz8ycjrl"
            target_weight: "100000000"
    claim:
      airdrops:
        - id: "1"
          source_address: "cosmos15rz2rwnlgr7nf6eauz52usezffwrxc0mz4pywr"
          conditions:
            - "CONDITION_TYPE_DEPOSIT"
            - "CONDITION_TYPE_SWAP"
            - "CONDITION_TYPE_LIQUIDSTAKE"
            - "CONDITION_TYPE_VOTE"
          start_time: "2022-02-01T00:00:00Z"
          end_time: "2022-03-21T00:00:00Z"
      claim_records:
        - airdrop_id: "1"
          recipient: "cosmos1zaavvzxez0elundtn32qnk9lkm8kmcszzsv80v"
          initial_claimable_coins:
            - amount: "3000000000000"
              denom: "airdrop"
          claimable_coins:
            - amount: "3000000000000"
              denom: "airdrop"
          claimed_conditions: