init:
  home: "$HOME/.crescent"
build:
  ldflags: ["-X github.com/crescent-network/crescent/v2/x/farming/keeper.enableAdvanceEpoch=true"]
accounts:
  - name: alice # cre1zaavvzxez0elundtn32qnk9lkm8kmcszxclz6p
    mnemonic: "guard cream sadness conduct invite crumble clock pudding hole grit liar hotel maid produce squeeze return argue turtle know drive eight casino maze host"
    coins: ["1500000000000stake", "1000000000000000uatom", "1000000000000000uusd"]
  - name: bob # cre1mzgucqnfr2l8cj5apvdpllhzt4zeuh2c5l33n3
    mnemonic: "friend excite rough reopen cover wheel spoon convince island path clean monkey play snow number walnut pull lock shoot hurry dream divide concert discover"
    coins: ["1000000000000stake", "1000000000000000uatom", "1000000000000000uusd"]
  - name: steve # cre185fflsvwrz0cx46w6qada7mdy92m6kx4vg42xf
    mnemonic: "fuel obscure melt april direct second usual hair leave hobby beef bacon solid drum used law mercy worry fat super must ritual bring faculty"
    coins: ["1000000000000stake", "1000000000000000uatom", "1000000000000000uusd"]
  - name: source # cre15rz2rwnlgr7nf6eauz52usezffwrxc0mxajpmw
    mnemonic: "diary behind allow lawn loop assault armor survey media toe rural mass skull way crater tobacco pair glare window soon lift pistol fitness annual"
    coins: ["15000000000000airdrop"]
validator:
  name: alice
  staked: "500000000000stake"
genesis:
  chain_id: "localnet"
  app_state:
    crisis:
      constant_fee:
        denom: "stake"
    mint:
      params:
        mint_denom: "stake"
    staking:
      params:
        bond_denom: "stake"
    gov:
      deposit_params:
        min_deposit:
          - amount: "1"
            denom: "stake"
    farming:
      params:
        private_plan_creation_fee:
          - amount: "100000"
            denom: "stake"
    liquidity:
      params:
        pair_creation_fee:
          - amount: "100000"
            denom: "stake"
        pool_creation_fee:
          - amount: "100000"
            denom: "stake"
    liquidstaking:
      params:
        liquid_bond_denom: "bstake"
        whitelisted_validators:
          - validator_address: "crevaloper1zaavvzxez0elundtn32qnk9lkm8kmcszyvldht"
            target_weight: "100000000"
    claim:
      airdrops:
        - id: "1"
          source_address: "cre15rz2rwnlgr7nf6eauz52usezffwrxc0mxajpmw"
          conditions:
            - "CONDITION_TYPE_DEPOSIT"
            - "CONDITION_TYPE_SWAP"
            - "CONDITION_TYPE_LIQUIDSTAKE"
            - "CONDITION_TYPE_VOTE"
          start_time: "2022-03-01T00:00:00Z"
          end_time: "2022-05-21T00:00:00Z"
      claim_records:
        - airdrop_id: "1"
          recipient: "cre1zaavvzxez0elundtn32qnk9lkm8kmcszxclz6p"
          initial_claimable_coins:
            - amount: "3000000000000"
              denom: "airdrop"
          claimable_coins:
            - amount: "3000000000000"
              denom: "airdrop"
          claimed_conditions: